book_review/book_review/urls.py
from django.contrib import admin
from django.urls import path, include
# Add this for image
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('reviews.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book_review/reviews/urls.py
#! /usr/bin/venv python3
# coding: utf-8
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    path("", views.connection_view, name="connection"),
    path("register/", views.register_view, name="register"),
    path("logout/", views.logout_view, name="logout"),
    path("home/", views.home_view, name="home"),

    path('tickets/create/', views.TicketCreateView.as_view(), name='ticket-create'),
    path('tickets/list/', views.TicketListView.as_view(), name='ticket-list'),
    path('tickets/<int:pk>/', views.TicketDetailView.as_view(), name='ticket-detail'),
    path('tickets/<int:pk>/update/', views.TicketUpdateView.as_view(), name='ticket-update'),
    path('tickets/<int:pk>/delete/', views.TicketDeleteView.as_view(), name='ticket-delete'),

    path('reviews/create/', views.create_new_ticket_review_view, name='review-create'),
    path('reviews/list/', views.ReviewListView.as_view(), name='review-list'),
    path('reviews/<int:pk>/', views.ReviewDetailView.as_view(), name='review-detail'),
    path('reviews/<int:pk>/update/', views.ReviewUpdateView.as_view(), name='review-update'),
    path('reviews/<int:pk>/delete/', views.ReviewDeleteView.as_view(), name='review-delete'),

    path("own_posts/", views.own_posts_view, name="own-posts"),

    path("user_follows/", views.user_follows_view, name="user-follows"),
    path('user_follows/<int:pk>/delete/', views.UserFollowsDeleteView.as_view(), name='user-follows-delete'),
]

book_review/reviews/forms.py
#! /usr/bin/venv python3
# coding: utf-8
"""Forms for book_review project.

Forms contain:
- NewUserForm which is used to register the site.
- MyAuthenticationForm which is used to login the site.
- TicketModelForm which is used to display some fields of Ticket model.
- ReviewModelForm which is used to display some fields of Review model.
- UserFollowsModelForm which is used to display some fields of UserFollows model.
"""

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm

from .models import Ticket, Review, UserFollows


class NewUserForm(UserCreationForm):
    """Form used to allow a new user registers the site."""

    class Meta:
        model = User
        fields = ("username", "password1", "password2")

    def __init__(self, *args, **kwargs):
        """Establish the elements to display the form in template."""

        super(NewUserForm, self).__init__(*args, **kwargs)
        for field_name in self.fields:
            self.fields[field_name].help_text = None
            self.fields[field_name].label = ""
        self.fields['username'].widget.attrs['placeholder'] = 'Nom d\'utilisateur'
        self.fields['password1'].widget.attrs['placeholder'] = 'Mot de pass'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirmer mot de passe'

    def save(self, commit=True):
        """Save new user in the database when the form is valid."""

        user = super(NewUserForm, self).save(commit=False)
        if commit:
            user.save()
        return user


class MyAuthenticationForm(AuthenticationForm):
    """Form used to allow the authentication of a user."""

    class Meta:
        model = User
        fields = ("username", "password")

    def __init__(self, *args, **kwargs):
        """Establish the elements to display the form in template."""

        super(MyAuthenticationForm, self).__init__(*args, **kwargs)
        for field_name in self.fields:
            self.fields[field_name].help_text = None
            self.fields[field_name].label = ""

        self.base_fields['username'].widget.attrs['placeholder'] = 'Nom d\'utilisateur'
        self.base_fields['password'].widget.attrs['placeholder'] = 'Mot de pass'


class TicketModelForm(forms.ModelForm):
    """Form to display Ticket's attributes."""

    title = forms.CharField(
        label='Titre',
        required=False,
    )

    description = forms.CharField(
        label="Description",
        required=False,
        widget=forms.Textarea(
            attrs={
                "class": "new-class-name two",
                "id": "my-id-for-textarea",
                "rows": 5,
                'cols': 50
            }
        )
    )

    class Meta:
        model = Ticket
        fields = ["title", "description", "image"]


class ReviewModelForm(forms.ModelForm):
    """Form to display Review's attributes."""

    RATING_RANGE = (
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5')
    )

    rating = forms.ChoiceField(
        label='Note',
        required=False,
        choices=RATING_RANGE,
        widget=forms.RadioSelect
    )

    headline = forms.CharField(
        label='Titre',
        required=False,
    )

    body = forms.CharField(
        label="Commentaire",
        required=False,
        widget=forms.Textarea(
            attrs={
                "class": "new-class-name two",
                "id": "my-id-for-textarea",
                "rows": 5,
                'cols': 50,
            }
        )
    )

    class Meta:
        model = Review
        fields = ["headline", "rating", "body"]


class UserFollowsModelForm(forms.ModelForm):
    """Form to display UserFollows' attributes."""

    class Meta:
        model = UserFollows
        fields = ["followed_user"]

    def __init__(self, *args, **kwargs):
        super(UserFollowsModelForm, self).__init__(*args, **kwargs)
        self.base_fields["followed_user"].widget.attrs['placeholder'] = 'Nom d\'utilisateur'

book_review/reviews/views.py
#! /usr/bin/venv python3
# coding: utf-8
"""Views for book_review project.

Main views:
- Connection page (for authentication)
- Registration page (to register the site)
- Home page (Flux view in the project: all posts of an authenticated user and which of his following users)
- Posts page (All posts (tickets and reviews) of an authenticated user)
- Abonnements page (to follow other users and to see who the user follows and who follows the user)
"""

from itertools import chain

from django.shortcuts import redirect
from django.template.context_processors import csrf
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages  # import messages
from django.shortcuts import render
from django.urls import reverse
from django.core.exceptions import ObjectDoesNotExist
from django.db import IntegrityError
from django.db.models import CharField, Value
from django.views.generic import (
    CreateView,
    DetailView,
    ListView,
    UpdateView,
    DeleteView
)

from .forms import (
    NewUserForm,
    MyAuthenticationForm,
    TicketModelForm,
    ReviewModelForm,
    UserFollowsModelForm
)

from .models import (
    Ticket,
    Review,
    UserFollows
)


def connection_view(request):
    """This view is used to login for a user."""

    if request.method == "POST":
        form = MyAuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("reviews:home")
        else:
            messages.error(
                request, "Nom d'utilisateur ou mot de passe invalide.")
    else:
        form = MyAuthenticationForm()
    context = {"login_form": form}
    return render(
        request=request,
        template_name='reviews/users/connection.html',
        context=context)


def register_view(request):
    """This view is used to register the site for a new user."""

    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Inscription effectuée avec succès")
            return redirect("reviews:connection")
        messages.error(
            request,
            "Le nom d'utilisateur ou le mot de passe est incorrect.")
    form = NewUserForm()
    return render(
        request=request,
        template_name="reviews/users/register.html",
        context={
            "register_form": form})


def logout_view(request):
    """This view is used to logout of the site."""

    logout(request)
    return redirect("reviews:connection")


def home_view(request):
    """The Home view used after a user is authenticated.

    This view displays all posts (tickets and reviews) related to the user and to his following users.
    """

    reviews = Review.get_users_viewable_reviews(request.user)
    # returns queryset of reviews
    reviews = reviews.annotate(content_type=Value('REVIEW', CharField()))

    tickets = Ticket.get_users_viewable_tickets(request.user)
    # returns queryset of tickets
    tickets = tickets.annotate(content_type=Value('TICKET', CharField()))

    # combine and sort the two types of posts
    posts = sorted(
        chain(reviews, tickets),
        key=lambda post: post.time_created,
        reverse=True
    )
    if request.method == "POST":
        if 'create_review' in request.POST:
            post_id = request.POST.get('create_review')  # post is a ticket
            request.session["ticket_id"] = post_id
            request.session["has_already_ticket"] = True
            return redirect("reviews:review-create")
    return render(request, "reviews/users/home.html", context={'posts': posts})


def own_posts_view(request):
    """The Posts view used to display all posts (tickets and reviews) of the authenticated user."""

    reviews = Review.get_reviews_posted_by_user(request.user)
    # returns queryset of reviews
    reviews = reviews.annotate(content_type=Value('REVIEW', CharField()))

    tickets = Ticket.get_tickets_created_by_user(request.user)
    # returns queryset of tickets
    tickets = tickets.annotate(content_type=Value('TICKET', CharField()))

    # combine and sort the two types of posts
    posts = sorted(
        chain(reviews, tickets),
        key=lambda post: post.time_created,
        reverse=True
    )

    if request.method == "POST":
        if request.POST.get("deletePost"):
            post_value = request.POST.get("deletePost")
            if "TICKET" in post_value:
                # The rest of string
                ticket_id = int(post_value[len("TICKET"):])
                ticket = request.user.tickets.get(id=ticket_id)
                title = ticket.title
                ticket.delete()
                messages.success(
                    request, f"Vous avez supprimé le ticket {title}")
            if "REVIEW" in post_value:
                # The rest of string
                review_id = int(post_value[len("REVIEW"):])
                review = Review.objects.get(id=review_id)
                ticket = review.ticket
                review.delete()
                messages.success(
                    request, f"Vous avez supprimé la critique {ticket} ")
            return redirect("reviews:own-posts")

    return render(
        request,
        "reviews/users/own_posts.html",
        context={
            'posts': posts})


def user_follows_view(request):
    """This view corresponds to Abonnement page.

     The user can select an user name of other users to follow him.

     The user can see all users who follows him and all users he follows.
     """

    if request.method == "POST":
        user = request.user
        try:
            if request.POST.get("will_follow_user") != "Nom d'utilisateur":
                will_follow_user_name = request.POST.get("will_follow_user")
                UserFollows.add_user_follows(user, will_follow_user_name)
                messages.success(request, "Le suivi est effectué.")
                return redirect("reviews:user-follows")
        except ObjectDoesNotExist:
            messages.error(request, "Le nom d'utilisateur n'existe pas")
        except IntegrityError:
            messages.error(request, "Vous avez déjà suivi cet utilisateur")
        else:
            messages.error(request, "Erreur de demande de suivi")

    form = UserFollowsModelForm()
    user = request.user
    following_users = UserFollows.get_following_user_follows_from_user(user)
    followed_users = UserFollows.get_followed_user_follows_from_user(user)
    context = {
        "following_users": following_users,
        "followed_users": followed_users,
        "form": form}
    return render(request, "reviews/users/user_follows.html", context=context)


class TicketCreateView(CreateView):
    """This view is used when the authenticated user wants to create a ticket."""

    template_name = 'tickets/ticket_create.html'
    form_class = TicketModelForm
    queryset = Ticket.objects.all()

    def form_valid(self, form):
        """Validate the input for creating a Ticket model."""

        form.instance.user = self.request.user  # To add logged user as the attribute "user" of Ticket
        return super().form_valid(form)

    def get_success_url(self):
        """Redirect to the Home page when the ticket is created with success."""

        return reverse('reviews:home')


class TicketListView(ListView):
    """This view is used when the authenticated user wants to see his all tickets."""

    template_name = 'tickets/ticket_list.html'
    queryset = Ticket.objects.all()


class TicketDetailView(DetailView):
    """This view is used when the authenticated user wants to see the detail of one of his tickets."""

    template_name = 'tickets/ticket_detail.html'
    queryset = Ticket.objects.all()


class TicketUpdateView(UpdateView):
    """This view is used when the authenticated user wants to update/modify one of his tickets."""

    template_name = 'tickets/ticket_update.html'
    form_class = TicketModelForm
    queryset = Ticket.objects.all()

    def form_valid(self, form):
        """Validate the updated information for a ticket."""

        return super().form_valid(form)

    def get_success_url(self):
        """Redirect to the Posts page when the ticket is updated with success."""

        return reverse('reviews:own-posts')


class TicketDeleteView(DeleteView):
    """This view is used when the authenticated user wants to delete one of his tickets."""

    template_name = 'tickets/ticket_delete.html'
    queryset = Ticket.objects.all()

    def get_success_url(self):
        """Redirect to the Posts page when the ticket is deleted."""

        return reverse('reviews:own-posts')


def create_new_ticket_review_view(request):
    """This view is used when the authenticated user wants to create his own review or reply to a ticket."""

    if request.method == "POST":
        if request.POST.get("new_ticket_review") == "new_ticket_review":
            ticket_form = TicketModelForm(request.POST, request.FILES)
            review_form = ReviewModelForm(request.POST)
            user = request.user
            if ticket_form.is_valid() and review_form.is_valid():
                print(ticket_form)
                ticket = ticket_form.save(False)
                ticket.user = user
                ticket.save()

                review = review_form.save(False)
                review.ticket = ticket
                review.user = user
                review.save()
                return redirect("reviews:home")
        if "already_ticket" in request.POST:
            ticket_id = request.POST.get("already_ticket")
            ticket = Ticket.objects.get(id=ticket_id)

book_review/reviews/templates/reviews/users/connection.html
<!--Connection page-->
{% extends 'reviews/includes/header.html' %}
{% block content %}
{% load crispy_forms_tags %}
<div class="container py-5">
    <h2 class="text-center">Connectez-vous</h2>
    <form method="POST">
        {% csrf_token %}
        {{ login_form|crispy }}
        <p class="text-center">
            <button class="btn btn-primary" type="submit" name="login">Se connecter</button>
        </p>
        <br>
        <br>
        <br>
        <h2 class="text-center">Inscrivez-vous maintenant</h2>
        <p class="text-center">
            <a class="btn btn-primary" href="{% url 'reviews:register' %}">S'inscrire</a>
        </p>
    </form>
</div>
{% endblock %}

book_review/reviews/templates/reviews/users/home.html
<!--Home page (Flux page in the project)-->
{% extends 'reviews/includes/header.html' %}
{% load static %}
{% block content %}
<div class="container py-5">
    <div ALIGN='center'>
        <a class="btn btn-primary" href="{% url 'reviews:ticket-create' %}">Demander une critique</a>
        <a class="btn btn-primary" href="{% url 'reviews:review-create' %}">Créer une critique</a>
    </div>
    <div class="container py-5">
        {% for post in posts %}
			{% if post.content_type == 'TICKET' %}
			    {% include 'reviews/includes/ticket_snippet.html' %}
			{% elif post.content_type == 'REVIEW' %}
			    {% include 'reviews/includes/review_snippet.html' %}
			{% endif %}
        </br>
        </br>
        {% endfor %}
    </div>
</div>
{% endblock %}

book_review/reviews/templates/reviews/users/own_posts.html
<!--Post page-->
{% extends 'reviews/includes/header.html' %}
{% block content %}
<div class="container py-5">
    <h1 class="text-center">Vos posts</h1>
    {% for post in posts %}
    <div class="border border-primary">
        <form action='.' method='POST'>
            {% csrf_token %}
            {% if post.content_type == 'TICKET' %}
                <div class="container py-5">
                    <p> Vous avez publié un ticket <span
                            class="badge badge-default float-right m-2">{{post.time_created}}</span></p>
                    {% include 'reviews/includes/ticket_info_snippet.html' %}
                    <br>
                    <br>
                    <a class="btn btn-primary" href="{% url 'reviews:ticket-delete' post.pk%}">Supprimer</a>
                    <a class="btn btn-primary" href="{% url 'reviews:ticket-update' post.pk%}">Modifier</a>
                </div>
            {% elif post.content_type == 'REVIEW' %}
                {% include 'reviews/includes/review_snippet_without_border.html' %}
                <div class="container py-5">
                    <a class="btn btn-primary" href="{% url 'reviews:review-delete' post.pk%}">Supprimer</a>
                    <a class="btn btn-primary" href="{% url 'reviews:review-update' post.pk%}">Modifier</a>
                </div>
            {% endif %}
        </form>
    </div>
    {% endfor %}
</div>
{% endblock %}

book_review/reviews/templates/reviews/users/register.html
<!--Signup page-->
{% extends 'reviews/includes/header.html' %}
{% block content %}
{% load crispy_forms_tags %}
<div class="container py-5 w-50">
    <h2 class="text-center">Inscrivez-vous</h2>
    <form action='.' method="POST" ALIGN='center'>
        {% csrf_token %}
        {{ register_form|crispy }}
        <a class="btn btn-primary" href="{% url 'reviews:connection' %}">Retourner</a>
        <button class="btn btn-primary">S'inscrire</button>
    </form>
</div>
{% endblock %}

book_review/reviews/templates/reviews/users/user_follows.html
<!--User follows page (Abonnements page in the project) -->
{% extends 'reviews/includes/header.html' %}
{% block content %}
<div class="container py-5">
    <div class="border border-primary">
        <div class="container py-5 w-75">
            <form action='.' method='POST' ALIGN='center'>
                {% csrf_token %}
                <div class="container py-5 w-50">
                    <h4 class="text-center">Suivre d'autres utilisateurs</h4>

                    <input type="text" name="will_follow_user" placeholder="Nom d'utilisateur">
                    <input class="btn btn-primary" type='submit' value='Envoyer'/>
                </div>

                <div class="container py-5 w-50">
                    <h4 class="text-center">Abonnements</h4>
                    <table class="table">
                        <tbody>
                        {% for following_user in following_users %}
                        <tr>
                            <td class="text-center">{{following_user.followed_user.username}}</td>
                            <td class="text-center">
                                <a class="btn btn-primary"
                                   href="{% url 'reviews:user-follows-delete' following_user.pk %}">Désabonner</a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>

                <div class="container py-5 w-50">
                    <h4 class="text-center">Abonnés</h4>
                    <table class="table">
                        <tbody>
                        {% for followed_user in followed_users %}
                        <tr>
                            <td class="text-center">{{followed_user.user.username}}</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

book_review/reviews/templates/reviews/users/user_follows_delete.html
<!--User deletion page (to confirm the deletation of an UserFollows object)-->
{% extends 'reviews/includes/header.html' %}
{% block content %}
    <form action='.' method='POST'>{% csrf_token %}
        <h1>Vous voulez désabonner l'utilisateur "{{ object.followed_user.username }}" ?</h1>
        <p><input type='submit' value='Oui' />  <a href="{% url 'reviews:user-follows' %}">Annuler</a></p>
    </form>
{% endblock %}